name: Nextjs EC2 Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Check Node v
        run: node -v

      - name: ⚙️ 환경변수를 설정합니다.
        working-directory: ./deploy
        run: |
          pwd
          touch .env
          echo DATABASE_URL=${{ secrets.MONGODB_URI }} >> .env

      - name: Install & Build
        run: |
          npm install
          npm run build

      - name: zip create
        run: zip -qq -r ./test-build.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 cp --region us-east-1 ./test-build.zip s3://nextjs-dynamic/test-build.zip

      - name: Deploy
        run: aws deploy create-deployment
          --application-name nextjs-codeDeploy
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name nextjs-codeDeploy-group
          --s3-location bucket=nextjs-dynamic,bundleType=zip
